// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/gin-gonic/gin"
	"net/http"
	"wiretest/service/bank"
	"wiretest/service/user"
)

// Injectors from server.go:

func NewApp() *App {
	bankService := bank.NewBankService()
	userService := user.NewUserService()
	app := &App{
		BankService: bankService,
		UserService: userService,
	}
	return app
}

// server.go:

type App struct {
	BankService bank.BankService
	UserService user.UserService
}

func (app App) Run() {
	r := gin.Default()

	r.GET("/bank", func(ctx *gin.Context) {
		ctx.String(http.StatusOK, app.BankService.GetBank())
	})
	r.GET("/user", func(ctx *gin.Context) {
		ctx.String(http.StatusOK, app.UserService.GetUser())
	})

	r.Run()
}
