// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/spf13/viper"
	"nunuim/internal/dao"
	"nunuim/internal/job"
	"nunuim/pkg/log"
)

// Injectors from wire.go:

// wire.go 初始化模块
func NewApp(viperViper *viper.Viper, logger *log.Logger) (*job.Job, func(), error) {
	db := dao.NewDB(viperViper)
	jobJob := job.NewJob(db, logger)
	return jobJob, func() {
	}, nil
}
